AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'

  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 100